[pytest]
addopts = 
    --headed
    --browser chromium
    --browser firefox
    --tracing retain-on-failure 
    --screenshot only-on-failure
    --video retain-on-failure
    -n auto
    -v
    --html=report.html
    --self-contained-html

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
